# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{alis}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Potapov Sergey"]
  s.date = %q{2011-08-29}
  s.default_executable = %q{alis}
  s.description = %q{In some cases alias UNIX command can't satisfy you. Alis allows you create more flexible aliases, for example to add default option --no-rdoc to 'gem install'}
  s.email = %q{blake131313@gmail.com}
  s.executables = ["alis"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "GPL-LICENSE.txt",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "alis.gemspec",
    "bin/alis",
    "features/alis.feature",
    "features/steps.rb",
    "features/support.rb",
    "lib/alis.rb",
    "lib/alis/alias.rb",
    "lib/alis/cmd.rb",
    "lib/alis/cmd_template.rb",
    "lib/alis/store.rb"
  ]
  s.homepage = %q{http://github.com/greyblake/alis}
  s.licenses = ["GNU GPL v2"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Tool to create flexible aliases.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<commander>, [">= 0"])
    else
      s.add_dependency(%q<commander>, [">= 0"])
    end
  else
    s.add_dependency(%q<commander>, [">= 0"])
  end
end

